ignoreWorkspaceRootCheck: true
strictPeerDependencies: false
packages:
  - playgrounds/*
allowBuilds:
  esbuild: true
  simple-git-hooks: true
minimumReleaseAgeExclude:
  - '@devframes/agentic@1.0.0'
  - '@devframes/hub-ui@1.0.0'
  - '@devframes/hub@1.0.0'
  - '@devframes/json-render-ui@1.0.0'
  - '@devframes/json-render@1.0.0'
  - '@devframes/next@1.0.0'
  - '@devframes/plugin-code-server@1.0.0'
  - '@devframes/plugin-data-inspector@1.0.0'
  - '@devframes/plugin-inspect@1.0.0'
  - '@devframes/plugin-messages@1.0.0'
  - '@devframes/plugin-terminals@1.0.0'
  - '@devframes/service-open@1.0.0'
  - '@devframes/vite@1.0.0'
  - '@nuxt/devtools-kit@4.0.0-beta.1'
  - '@nuxt/devtools@4.0.0-beta.1'
  - '@vitejs/devtools-kit@0.7.5'
  - '@vitejs/devtools@0.7.5'
  - 'devframe@1.0.0'
patchedDependencies:
  '@vitejs/devtools@0.7.5': patches/@vitejs__devtools@0.7.5.patch
